image: node:10.3.0

stages:
  - test
  - deploy

before_script:
  - yarn

run-unit-test:
  stage: test
  script:
    - yarn test

deploy-staging:
  stage: deploy
  script:
    - yarn deploy:staging:ci
  only:
    - staging
    - merge_requests

deploy-production:
  stage: deploy
  script:
    - yarn deploy:prod:ci
  only:
    - master
    - merge_requests
