image: node:10.3.0

stages:
  - test
  - deploy

before_script:
  - yarn

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

run-unit-test:
  stage: test
  script:
    - yarn test
  only:
    - pushes

deploy-staging:
  stage: deploy
  script:
    - yarn deploy:staging:ci
  only:
    - staging
    - merge_requests

deploy-production:
  stage: deploy
  script:
    - yarn deploy:prod:ci
  only:
    - master
    - merge_requests
